# Generated by Django 5.0.1 on 2024-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gros', '0002_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
