# Generated by Django 5.0.1 on 2024-03-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gros', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_object',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
