# Generated by Django 5.0.1 on 2024-03-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gros', '0005_remove_product_qty_remove_stock_product_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='basket_item_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gros.basketitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('intransit', 'intransit'), ('dispatched', 'dispatched'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order-placed', max_length=200),
        ),
    ]
