# Generated by Django 5.0.1 on 2024-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gros', '0006_orderitems_basket_item_object_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
