# Generated by Django 5.0.1 on 2024-03-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gros', '0007_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
