# Generated by Django 5.0.1 on 2024-03-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gros', '0008_basketitem_is_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
